[package]
name = "silver3d"
version = "0.1.0"
authors = ["SOMEONE360 <61124185+SOMEONE360@users.noreply.github.com>"]
edition = "2018"

[dependencies]
landon = "0.10.1"
wasm-bindgen = "0.2.71"
web-sys = "0.3.48"
